

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages

```{r}
# If you are on a new machine you haven't used before, you may need to install these packages before loading.  If that's the case, remove the comment # from in front of the next two lines before running the codeblock, to install the packages before loading.
# install.packages('tidyverse')
# install.packages('vembedr')

# Load the tidyverse, vembedr
library(tidyverse)
library(vembedr)
library(janitor)
library(lubridate)

```

## Load data

```{r}
heritage <- read_csv("data/whose_heritage.csv") %>%
  clean_names()
```

## Exploratory analysis

``` {r}

heritage %>%
  group_by(honorees) %>%
  count() %>%
  arrange(desc(n))

```

``` {r}

heritage %>%
  group_by(state) %>%
  count() %>%
  arrange(desc(n))

```

``` {r}

heritage %>%
  group_by(symbol_type) %>%
  count() %>%
  arrange(desc(n))

```

``` {r}

heritage %>%
  group_by(year_removed) %>%
  count() %>%
  arrange(desc(n))

```

``` {r}

heritage %>%
  group_by(symbol_category, symbol_type, state) %>%
  count() %>%
  arrange(desc(n))

```





## Data Analysis Project #2, group 2:

2) How many monuments in Cali have come down? When were they taken down — before/after Floyd?

```{r}
# part 1: How many monuments in Cali have come down?
cali_monuments_down <- heritage %>%
  filter(state == "CA") %>%
  filter(tracking_status %in% c("Removed", "Renamed"))
 
cali_monuments_down

# A: 6
```

```{r}
# part 2: When were they taken down — before/after Floyd?
cali_monuments_down_bf_floyd <- cali_monuments_down %>%
  filter(year_removed < 2020,) %>%
  arrange(desc(year_removed))
 
cali_monuments_down_bf_floyd

# Before Floyd: *5 (see answer below for reasoning behind "*"). two in 2016, and one in 2017, 2018 and 2019.

cali_monuments_down_af_floyd <- cali_monuments_down %>%
  filter(year_removed >= 2020) %>%
  arrange(desc(year_removed))
 
cali_monuments_down_af_floyd

# After Floyd: *1, in 2020. George Floyd was killed in 2020 and only one monument was removed/renamed in that year. Floyd was killed in the spring, so it's possible that this monument was taken down prior to his death, but given the large-scale removal of confederate monuments in the wake of his death, it's more likely that this monument was taken down in reaction to the tragedy and the unrest that followed. 
```

